runtime: nodejs12
env: flex

env_variables:
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""
  POSTGRES_DATABASE:  "url_shortener"
  POSTGRES_HOST: ""
  SERVER_PORT: "3000"
  API_KEY: ""

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
